feat: add detection support for the commit sha on all CI providers

diff --git a/bin/dokku-deploy b/bin/dokku-deploy
--- a/bin/dokku-deploy
+++ b/bin/dokku-deploy
@@ -3,6 +3,7 @@ set -e
 
 setup-ssh
 
+commit_sha="$(parse-ci-commit)"
 app_name="$(parse-app-name)"
 ssh_remote="ssh://dokku@$(parse-ssh-host):$(parse-ssh-port)"
 
@@ -30,6 +31,11 @@ if [ -n "$COMMAND" ] && [ "$COMMAND" != "review-apps:create" ] && [ "$COMMAND" !
   exit 1
 fi
 
+if [ -z "$commit_sha" ]; then
+  log-error "Unable to detect commit sha"
+  exit 1
+fi
+
 if [ "$COMMAND" = "review-apps:create" ]; then
   log-info "Ensuring review app '${REVIEW_APP_NAME}' exists"
   ssh "$ssh_remote" -- apps:clone --skip-deploy --ignore-existing "$app_name" "$REVIEW_APP_NAME"
@@ -41,4 +47,4 @@ if [ -n "$REVIEW_APP_NAME" ] && [ "$app_name" != "$REVIEW_APP_NAME" ]; then
   GIT_REMOTE_URL="${GIT_REMOTE_URL%"/$app_name"}/${REVIEW_APP_NAME}"
 fi
 
-git push "$GIT_PUSH_FLAGS" "$GIT_REMOTE_URL" "$GITHUB_SHA:refs/heads/$BRANCH" --force
+git push "$GIT_PUSH_FLAGS" "$GIT_REMOTE_URL" "$commit_sha:refs/heads/$BRANCH" --force
